plugins {
    id 'application'
    id "me.champeau.jmh" version "0.7.0"
}

group = 'ru.leo.rank'
version = '1.0-SNAPSHOT'

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation 'com.expleague:commons:1.4.10-SNAPSHOT'
    implementation 'org.apache.commons:commons-lang3:3.17.0'
    implementation 'com.expleague:jmll:1.5.0-SNAPSHOT'
    implementation 'org.json:json:20250107'
//    implementation 'com.expleague:experiments:1.4.10-SNAPSHOT'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation platform('org.assertj:assertj-bom:3.27.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
    implementation 'ai.catboost:catboost-prediction:1.2'
    implementation 'it.unimi.dsi:fastutil:8.5.15'

    implementation platform("org.apache.logging.log4j:log4j-bom:2.25.1")

    implementation("org.apache.logging.log4j:log4j-core")
    implementation("org.apache.logging.log4j:log4j-slf4j-impl")
//    implementation("org.apache.logging.log4j:log4j-slf4j2-impl")
    implementation("org.apache.logging.log4j:log4j-api")
    implementation("org.apache.logging.log4j:log4j-jul")
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
}

test {
    useJUnitPlatform()
    jvmArgs '-Xms8g', '-Xmx10g'
    jvmArgs '-DloggingAppender=LocalAppender'
    jvmArgs '-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager'
}